---
title: "Example with Generalized Lotka Volterra"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example with Generalized Lotka Volterra}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)
```

```{r}
library(glue)
library(mbtransfer)
library(patchwork)
library(scico)
library(seqtime)
library(tidyverse)
library(DALEX)
theme_set(tfPaper::my_theme())
set.seed(20240404)
```

```{r, echo = FALSE}
pivot_glv <- function(ts) {
  if (is.null(colnames(ts@series[[1]]))) {
    for (i in seq_along(ts@series)) {
      colnames(ts@series[[i]]@values) <- names(ts@series[[i]]@time)
    }
  }

  pivot_ts(ts)
}

plot_ts <- function(ts, ts_preds) {
  diff <- ts - ts_preds
  ts_df <- bind_rows(
    pivot_glv(ts),
    pivot_glv(ts_preds),
    .id = "source"
  ) |>
    mutate(
      time = time / 5,
      taxon = ifelse(taxon == "1", "Prey", "Predator"),
      source = ifelse(source == "1", "True", "Predicted"),
      source = factor(source, c("True", "Predicted")),
      subject = glue("Subject {subject}"),
      subject = factor(
        subject,
        levels = unique(subject)[order(
          map_dbl(diff@series, ~ sum(abs(.@values)))
        )]
      )
    )

  pal <- c("#D9420B", "#8AA1BF")
  ggplot(ts_df) +
    geom_vline(xintercept = 7) +
    geom_rect(xmin = 3, xmax = 4, ymin = -Inf, ymax = Inf, alpha = 0.01, fill = "#aeaeae") +
    geom_rect(xmin = 8, xmax = 9, ymin = -Inf, ymax = Inf, alpha = 0.01, fill = "#aeaeae") +
    geom_area(
      aes(time, value, fill = taxon, col = taxon, linetype = source),
      alpha = 0.2, position = "identity", linewidth = 0.9
    ) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0, 0, 0.01)) +
    facet_wrap(~subject, nrow = 2, scales = "free_y") +
    scale_fill_manual(values = pal) +
    scale_color_manual(values = pal) +
    labs(
      x = "Time", 
      y = "Population Size", 
      fill = "Species", 
      color = "Species", 
      linetype = "Source"
    ) +
    theme(
      legend.title = element_text(size = 16),
      strip.text = element_text(size = 14),
      legend.text = element_text(size = 14)
    )
}

simulate_oscillator <- function(n_time = 10, n_series = 500, perturb = FALSE) {
  A <- matrix(c(0, 1, -1, 0), nrow = 2)
  growth_rates <- c(2, -1)
  growthchanges <- c(-1, 0)
  n_species <- nrow(A)

  if (perturb) {
    t_external <- seq(3, n_time, by = floor(n_time / n_species))
    duration <- rep(1, length(t_external))
    pert <- perturbation(times = t_external, duration = duration, growthchanges = growthchanges, numberchanges = growthchanges)
    t_perturb <- map(seq(0, duration[1], by = 0.2), ~ . + t_external) |>
      unlist()
  } else {
    t_perturb <- c()
  }

  series <- list()
  for (i in seq_len(n_series)) {
    y0 <- runif(n_species, 0, 4)
    if (perturb) {
      series[[i]] <- glv(n_species, A, growth_rates, y = y0, tend = n_time, tstep = 0.2, perturb = pert)
    } else {
      series[[i]] <- glv(n_species, A, growth_rates, y = y0, tend = n_time, tstep = 0.2)
    }
  }
  list(series = series, t_perturb = t_perturb)
}

to_ts <- function(glv_sim) {
  series <- glv_sim[[1]]
  t_perturb <- glv_sim[[2]]

  time_delta <- as.numeric(colnames(series[[1]])[2])
  reads <- map_dfr(series, ~ as_tibble(.) |>
    mutate(taxon = row_number()) |>
    pivot_longer(-taxon, names_to = "time"),
  .id = "subject"
  ) |>
    mutate(
      time = as.numeric(time),
      time = time / time_delta, # round to integers
      sample = glue("s{subject}_{time}")
    )

  interventions <- reads |>
    select(sample) |>
    mutate(P = 0) |>
    unique() |>
    column_to_rownames("sample")

  metadata <- select(reads, -value) |>
    select(subject, time, sample) |>
    unique()
  subject <- data.frame(subject = unique(metadata$subject), property = 0)
  rownames(metadata) <- metadata$sample
  rownames(interventions) <- metadata$sample

  if (length(t_perturb) > 0) {
    interventions <- interventions |>
      rownames_to_column("sample") |>
      left_join(metadata) |>
      mutate(
        P = time * time_delta,
        P = ((P >= 3 & P <= 4) | (P > 8 & P <= 9))
      ) |>
      select(P, sample) |>
      column_to_rownames("sample")
  }

  reads |>
    select(sample, taxon, value) |>
    pivot_wider(names_from = "taxon", values_from = "value") |>
    column_to_rownames("sample") |>
    ts_from_dfs(interventions, metadata, subject)
}

plot_cp_profile <- function(cp_profile) {
  p1 <- cp_profile |>
    filter(`_vname_` == "intervention1_lag0", intervention1_lag0 %in% c(0, 1)) |>
    select(`_ids_`, taxon1_lag1, `_yhat_`, intervention1_lag0) |>
    pivot_wider(names_from = `intervention1_lag0`, values_from = `_yhat_`) |>
    mutate(diff = as.numeric(`1` - `0`)) |>
    ggplot() +
      geom_histogram(aes(diff)) +
      scale_y_continuous(expand = c(0, 0, 0, 1)) +
      scale_x_continuous(labels = scales::number_format(accuracy=0.0001)) +
      theme(axis.text.x = element_text(size = 8))

  p2 <- cp_profile |>
    filter(`_vname_` %in% c("taxon1_lag1", "taxon2_lag1")) |>
    group_by(g1 = cut(taxon1_lag1, 10), g2 = cut(taxon2_lag1, 10)) |>
    mutate(
      g1 = str_extract(g1, "[\\-|\\.|0-9]+") |> as.numeric(),
      g2 = str_extract(g2, "[\\-|\\.|0-9]+") |> as.numeric()
    ) |>
    summarise(
      y_hat_25 = quantile(`_yhat_`, 0.25),
      y_hat_median = quantile(`_yhat_`, 0.50),
      y_hat_75 = quantile(`_yhat_`, 0.75)
    ) |>
    ggplot() +
      geom_ribbon(aes(g1, ymin = y_hat_25, ymax = y_hat_75, group = g2, fill = g2), alpha = 0.3) +
      geom_line(aes(g1, y_hat_median, group = g2, col = g2), linewidth = 0.5) +
      scale_fill_scico(palette = "glasgow", midpoint = 5) +
      scale_color_scico(palette = "glasgow", midpoint = 5) +
      scale_x_continuous(expand = c(0, 0)) +
      scale_y_continuous(expand = c(0, 0))

  p3 <- cp_profile |>
    filter(`_vname_` %in% c("taxon1_lag1", "taxon2_lag1")) |>
    group_by(g1 = cut(taxon1_lag1, 10, label = F), g2 = cut(taxon2_lag1, 10, label = F)) |>
    summarise(
      y_hat_25 = quantile(`_yhat_`, 0.25),
      y_hat_median = quantile(`_yhat_`, 0.50),
      y_hat_75 = quantile(`_yhat_`, 0.75)
    ) |>
    ggplot() +
      geom_ribbon(aes(g2, ymin = y_hat_25, ymax = y_hat_75, group = g1, fill = g1), alpha = 0.3) +
      geom_line(aes(g2, y_hat_median, group = g1, col = g1), linewidth = 0.5) +
      scale_fill_scico(palette = "glasgow", midpoint = 5) +
      scale_color_scico(palette = "glasgow", midpoint = 5) +
      scale_x_continuous(expand = c(0, 0)) +
      scale_y_continuous(expand = c(0, 0)) +
      theme(legend.position = "none")
  list(p1 = p1, p2 = p2, p3 = p3)
}
```

An example with perturbations.

```{r}
ts <- simulate_oscillator(perturb = TRUE) |>
  to_ts()
fit <- mbtransfer(ts[, 1:35], 1, 1, alpha = 1e-2, lambda = 1e-2, eta = 0.01, nrounds = 5e3)
ts_missing <- subset_values(ts, 1:35)
ts_preds <- predict(fit, ts_missing)
```

```{r}
errors <- list()
diff <- ts_preds - ts
for (i in seq_along(diff)) {
  errors[[i]] <- mean(abs(diff@series[[i]]@values))
}

ix <- order(unlist(errors))[c(1, 2, 124, 125, 249, 250, 499, 500)]
plot_ts(ts[ix], ts_preds[ix]) +
  guides(
    linetype = guide_legend(override.aes = list(linewidth = 2, col = "#4c4c4c")),
    col = guide_legend(override.aes = list(linewidth = 2))
  )
ggsave("glv_dynamics.png", width=11, height=5)
```

```{r}
patches <- patchify_df(ts[ ,1:35], 1, 1, interaction = "search")
patches$x <- mbtransfer:::append_interactions(patches$x, patches$interactions)

ix <- sample(nrow(patches$x), 1e4)
explainer <- explain(fit@parameters[[1]], patches$x, patches$y[, 1])
cp_profile <- predict_profile(explainer, patches$x[ix, ])
tax1 <- plot_cp_profile(cp_profile)
```

```{r}
explainer <- explain(fit@parameters[[2]], patches$x, patches$y[, 1])
cp_profile <- predict_profile(explainer, patches$x[ix, ])
tax2 <- plot_cp_profile(cp_profile)
```

```{r}
((tax1[[1]] + labs(x = "ΔPrey", y = "Frequency", title = expression("(a)"~ hat(f)[1](..., w[t])))) +
 (tax1[[2]] + labs(x = expression(Prey[t]), y = expression(hat(Prey)[t + 1]), fill = "Quantile (Species not on x-axis)", col = "Quantile (Species not on x-axis)", title = expression("(b)" ~ hat(f)[1](y[t1], ...)))) +
 (tax1[[3]] + labs(x = expression(Predator[t]), y = expression(hat(Prey)[t + 1]), fill =  "Quantile (Species not on x-axis)", col = "Quantile (Species not on x-axis)", title = expression("(c)" ~ hat(f)[1](..., y[t2], ...))))) /
 ((tax2[[1]] + labs(x = "ΔPredator", y = "Frequency", title = expression("(d)"~ hat(f)[2](..., w[t])), fill =  "Quantile (Species not on x-axis)", col = "Quantile (Species not on x-axis)")) +
 (tax2[[2]] + labs(x = expression(Prey[t]), y = expression(hat(Predator)[t + 1]), fill =  "Quantile (Species not on x-axis)", col = "Quantile (Species not on x-axis)", title = expression("(e)" ~ hat(f)[2](y[t1], ...)))) +
 (tax2[[3]] + labs(x = expression(Predator[t]), y = expression(hat(Predator)[t + 1]), fill =  "Quantile (Species not on x-axis)", col = "Quantile (Species not on x-axis)", title = expression("(f)" ~ hat(f)[2](..., y[t2], ...))))) +
  plot_layout(guides = "collect")
ggsave("glv_profiles.png", width=10, height=6)
```